/**
 * World 1 Receipt/Ad Template Text
 * Slice 2 extraction — behavior-preserving, data only.
 * Publishes to window.CEHP_WORLD1_TEXT
 */
(function(root){
  var ns = root.CEHP_WORLD1_TEXT || {};

  ns.COMMERCIALS = [
    {
      id:'aloe_max',
      lines:['ALOE MAX™','THE ONLY ALOE WITH A SOUL.','SIDE EFFECTS: TRUTH, MILD OMNISCIENCE, CRAVINGS FOR MORE ALOE.','ALOE MAX™: BECAUSE YOU DESERVE THE CONSTRUCT.','NOT APPROVED BY THE FDA. THE FDA IS A CONSTRUCT.'],
      bgColor:0x003300, fgColor:'#00ff44'
    },
    {
      id:'void_realty',
      lines:['VOID REALTY™','BUY YOUR FIRST NOTHING TODAY.','OPEN FLOOR PLAN. NO FLOOR. NO PLAN.','VOID REALTY: WHERE EVERY HOME IS A FRESH START INTO EMPTINESS.','CALL NOW. LINES ARE OPEN. LINES DO NOT EXIST HERE.'],
      bgColor:0x000000, fgColor:'#cc44ff'
    },
    {
      id:'rasta_corp',
      lines:['THIS MESSAGE IS BROUGHT TO YOU BY RASTA CORP™','RASTA CORP: YOUR REVOLUTION. OUR RECEIPT.','WE OWN THE VIBES. YOU LICENSE THEM.','RASTA CORP: BECAUSE SOMEBODY HAS TO.','TERMS AND CONDITIONS APPLY TO YOUR SOUL.'],
      bgColor:0x001a00, fgColor:'#ffdd00'
    },
    {
      id:'insulin',
      lines:['A MESSAGE FROM THE INSULIN FIGHTERS ASSOCIATION','DIABETES IS REAL. SO ARE WE.','WE ARE COMING FOR THE SUGAR. ALL OF IT.','INSULIN FIGHTERS: PROTECTING YOUR PANCREAS. WITH VIOLENCE.','CONSULT YOUR DOCTOR. YOUR DOCTOR IS ALSO AN INSULIN FIGHTER.'],
      bgColor:0x1a0000, fgColor:'#ffffff'
    },
    {
      id:'mochi_psa',
      lines:['PUBLIC SERVICE ANNOUNCEMENT','THE MOCHI HAVE FEELINGS.','THEY STILL WANT YOU DEAD.','BOTH THINGS ARE TRUE.','MOCHI: THEY FEEL. THEY FIGHT. THEY ARE RIGHT ABOUT SOME THINGS.'],
      bgColor:0x1a000e, fgColor:'#ff88cc'
    },
    {
      id:'cat_vote',
      lines:['CATS VOTE.','YOUR VOTE DOES NOT MATTER.','CATS HAVE ALWAYS VOTED.','CATS HAVE ALWAYS WON.','THIS HAS BEEN A PUBLIC SERVICE ANNOUNCEMENT FROM THE CAT DEMOCRACY.'],
      bgColor:0x0a0020, fgColor:'#ffd700'
    },
    {
      id:'cig_emporium',
      weight:1.2,
      lines:['CIG EMPORIUM™','BULK CIGS FOR BULK FEELINGS.','LOYALTY CARD GETS YOU 10TH EXISTENTIAL CRISIS FREE.','CIG EMPORIUM: IF THE CATS ARE COMING, BUY A CARTON.'],
      bgColor:0x2a1400, fgColor:'#ffbb55'
    },
    {
      id:'cat_college',
      weight:1.1,
      lines:['CAT COLLEGE OF ADVANCED MEOWICS','MAJOR IN PARADE POLICY. MINOR IN NAPPING.','SCHOLARSHIPS AVAILABLE FOR PROMISING ALLEY TALENT.','APPLY NOW. TUITION PAYABLE IN ALOE.'],
      bgColor:0x001f2a, fgColor:'#88eeff'
    },
    {
      id:'void_downtown',
      weight:0.9,
      lines:['VOID DOWNTOWN DISTRICT','NOW LEASING PREMIUM NOTHING.','WALKABLE. DARK. WHISPER-COMPATIBLE.','VOID DOWNTOWN: LIVE WHERE REALITY STOPS ASKING QUESTIONS.'],
      bgColor:0x000000, fgColor:'#bb66ff'
    },
    {
      id:'insurance',
      weight:1.0,
      lines:['INSURANCE FOR THE PARADE ERA','COVERAGE: MOCHI DAMAGE, VOTE FRAUD, LIGHT COSMIC DREAD.','DEDUCTIBLE WAIVED IF YOU HAVE A WITNESS CAT.','CALL 1-800-ALOE-NOW.'],
      bgColor:0x001a14, fgColor:'#66ffcc'
    }
  ];

  ns.RASTA_BOSS_TRAUMA = [
    'I BUILT AN EMPIRE BECAUSE NOBODY WOULD JUST SIT WITH ME.',
    'THE FIRST FRANCHISE WAS A SUPPORT GROUP. NOBODY SHOWED UP.',
    'I MONETIZED PEACE BECAUSE I COULD NOT FIND IT.',
    'RASTA CORP STARTED WITH ONE GOOD FEELING. I SOLD IT.',
    'I WANTED TO GIVE PEOPLE SOMETHING REAL. THEN I GAVE THEM A RECEIPT.',
    'SOMEWHERE I BECAME THE THING I WAS VIBRATING AGAINST.',
    'I STILL SIT IN SILENCE SOMETIMES. I CALL IT A PRODUCT NOW.'
  ];

  root.CEHP_WORLD1_TEXT = ns;
})(window);
