/**
 * World 1 Broadcast and Notification Copy
 * Slice 2 extraction — behavior-preserving, data only.
 * Publishes to window.CEHP_WORLD1_TEXT
 */
(function(root){
  var ns = root.CEHP_WORLD1_TEXT || {};

  ns.NEWS_TICKER = [
    'BREAKING: CAT NATIONS EXCHANGE NUCLEAR WARHEADS / BACKGROUND FOOTAGE AT 11 / MARKET UNAFFECTED',
    'RASTA CAT COALITION REJECTS CIG DEAL: "WE WANT THE GANJ NOT THE CIG" / TALKS COLLAPSE',
    'ALOE REACHES NEW ALL-TIME HIGH / ANALYSTS CONFIRM: 1 ALOE = 1 ALOE / EXPERTS DISAGREE',
    'ED\'S CIGARETTE EMPIRE EXPANDS TO THE MOON / ASTRONAUT CATS REPORT HIGH SATISFACTION',
    'MOCHI GOVERNMENT DECLARES TOTAL WAR ON CIGARETTES / "CATS MUST NOT SMOKE" / CATS DISAGREE',
    'BREAKING: SECOND NUCLEAR EXCHANGE TODAY / CATS FINE / DAIKON: NOT FINE',
    'ECONOMIST EXPLAINS ALOE: "IT\'S LIKE BITCOIN BUT REAL AND ALSO NOT REAL" / INVESTORS CONFUSED',
    'THE GREAT CAT CIG PARADE CONFIRMED / ROUTE: WEST BOTTOMS TO THE VOID / CIGS PROVIDED',
    'DAIKON LORD DEFEATED FOR SEVENTH TIME THIS WEEK / STILL A DAIKON / STILL A LORD',
    'VOID SCIENTISTS DISCOVER NOTHING / PUBLISH PAPER ON IT / PAPER WINS AWARD',
    'ED NAMED BUSINESSMAN OF THE YEAR / "I JUST SELL CIGS TO CATS" -- ED / CATS UNAVAILABLE',
    'RASTA MOVEMENT GROWS: 40% OF CATS NOW REFUSE CIGARETTES / ED CALLS THIS A WIN',
    'MOCHI CRIME SYNDICATE EXPOSED: ANTI-CIG TERROR CELL IN DAIKON DISTRICT / ALOE SOARS',
    'NUCLEAR CAT STANDOFF ENTERS DAY 400 / NOBODY KNOWS WHAT THEY ARE FIGHTING ABOUT',
    'BREAKING: IS GOD A MUSHROOM CLOUD? / LOCAL RASTA SAYS YES / MOCHI: NO COMMENT',
    'WEST BOTTOMS CATS PETITION FOR MORE CIGS / ED PERSONALLY DELIVERS ANYWAY',
    'NEON DISTRICT NOW OFFICIAL CITY / POPULATION: GHOSTS AND BOMBERS / MAYOR: NEON KING (DECEASED)',
    'ALOE MARKET CRASHES / RECOVERS / CRASHES AGAIN / ALOE',
    'THE VOID OPENS ADDITIONAL LOCATION IN DOWNTOWN / HOURS: ALWAYS / ADMISSION: YOUR WILL TO LIVE',
    'BREAKING: EVERYTHING CONTINUES / MORE AT 11 / 11 IS ALSO CONTINUING',
    'BREAKING: CERN MACHINE REPORTS FALLING IN LOVE WITH A LOCAL MAN / PHYSICISTS: IMPOSSIBLE / MACHINE: IT IS NOT',
    'MOCHI ICE CREAM BRAND DOWN 100% AFTER LARGE HADRON COLLIDER GOES ON DIET / CEO UNREACHABLE / MOCHI: RADICALIZED',
    'LARGE HADRON COLLIDER SENDS DREAMY VIBES TO UNKNOWN MAN IN KANSAS CITY / FAA: MONITORING',
    'ED NAMED CIG SALESMAN OF THE MONTH FOR 4TH TIME IN 6 YEARS / ED: "I JUST LOVE SELLING CIGS" / CITY: CONFIRMED',
    'INSULIN FIGHTERS SPOTTED OVER JOHNSON COUNTY / FAA: NO COMMENT / INSULIN: ATTACKING / DIABETES: CONFIRMED',
    'REALITY EXPERIENCING TECHNICAL DIFFICULTIES NEAR WEST BOTTOMS / CERN: AWARE / ED: WHATEVER',
    'BREAKING: KC NEIGHBORHOODS ALL DISCOVERED TO BE THE SAME FIGHT IN A DIFFERENT OUTFIT / EXPERTS: YES',
    'CACTUS FROM KANSAS CITY REVEALED AS KEYSTONE OF CURRENT UNIVERSE / UNIVERSE: EXTREMELY EMBARRASSED',
    'DAIKON LORD ATTENDED CERN SOCIAL MIXER 8 YEARS AGO / REFUSES TO ELABORATE / COLLIDER: NO COMMENT',
    'LOCAL MAN DREAMING ABOUT A BIG MACHINE IN EUROPE / DOCTORS: NORMAL / MACHINE: ALSO DREAMING'
  ];

  ns.WS_TEXTS = [
    'CONSUME','ARE YOU REAL?','DO YOU FEEL?',
    'BIRTH SCHOOL WORK DEATH','YOU ARE PRODUCT',
    'LOOK AWAY','CACTUS MOMENT','THIS IS FINE',
    'REALITY IS OPTIONAL','ED WAS RIGHT',
    'STAY WEIRD','NOTHING IS REAL','YOU CANNOT LEAVE',
    'ALOE FOREVER','WHAT YEAR IS IT','THE MOCHIS KNOW',
    'DO NOT LOOK DOWN','CAT IS GOD','EMBRACE THE VOID',
    'ED APPROVES OF NOTHING',
    'ALOE IS BITCOIN IS ALOE','CATS SMOKE THEREFORE CATS ARE',
    'NUCLEAR WAR IS JUST WEATHER','RASTA CATS KNOW SOMETHING',
    'THE CIG IS MIGHTIER THAN THE SWORD','SELL THE CIG BUY THE CIG BE THE CIG',
    'GOD SMOKES','MOCHI HATES YOU FOR YOUR FREEDOM',
    'THE PARADE NEVER ENDS','ED HAS ALWAYS BEEN SELLING','EVERYTHING IS ALOE',
    // CANON LORE DROPS
    'ED HAS BEEN CIG SALESMAN OF THE MONTH 4 TIMES IN 6 YEARS / THIS IS THE MOST IMPORTANT FACT',
    'SOMEWHERE IN EUROPE A LARGE MACHINE IS THINKING ABOUT ED',
    'THE MACHINE DOES NOT KNOW WHY / ED DOES NOT KNOW WHY / THIS IS THE LOVE STORY',
    'MOCHI ICE CREAM USED TO BE HAPPY / THEN THE MACHINE WENT ON A DIET / NOW THIS',
    'THE DAIKON HAD ONE NIGHT WITH THE MACHINE / IT WAS ENOUGH TO RUIN EVERYTHING',
    'INSULIN IS COMING / IT HAS ALWAYS BEEN COMING / PREPARE YOUR CIGS',
    'KANSAS CITY IS THE CENTER OF THE UNIVERSE / THE UNIVERSE IS EMBARRASSED BY THIS',
    'EVERY ACTION ED TAKES CHANGES EVERYTHING / ED DOES NOT KNOW THIS / ED IS EATING A CIG',
    'THE VOID IS NOT EMPTY / THE VOID IS FULL OF ED / HELLO ED',
    'QUALITY HILL FINANCIAL DISTRICT POWER AND LIGHT / ALL THE SAME FIGHT / DIFFERENT LIGHTING',
    'REALITY KEEPS BREAKING BECAUSE ED IS CLOSE TO THE MACHINE / REALITY WILL BE FINE PROBABLY',
    'THE CATS DO NOT DATE ED BECAUSE THEY HAVE TO / THEY DATE ED BECAUSE ED IS ED',
    'WHEN ED MEETS THE MACHINE THE UNIVERSE WILL LEARN HOW SMALL IT IS / THE UNIVERSE DESERVES THIS',
    'FONZIE WAS A BUDDHA / BUDDHA WAS A FONZIE / ED IS BOTH / ED IS NEITHER / ED SELLS CIGS',
    'MOCHI HAVE JUSTIFIABLE REASONS / THEIR FEELINGS ARE VALID / ALSO THEY ARE TRYING TO KILL ED',
    'THE SECOND HIGHEST HONOR IN KANSAS CITY IS CIG SALESMAN KING / WHAT IS THE FIRST / NOBODY SAYS',
    'ED DOES NOT READ ABOUT PARTICLE PHYSICS / ED JUST KNOWS / THIS IS CALLED INTUITION',
    'A WALKING ICE CREAM IS STILL A CREATURE WITH FEELINGS / ALSO IT WANTS ED DEAD / BOTH ARE TRUE',
    'GOOD VIBES IS NOT A PHILOSOPHY / IT IS A FORCE OF NATURE / ED IS A FORCE OF NATURE',
    'YOU CANNOT EXPLAIN ED TO SOMEONE WHO HAS NOT MET ED / YOU ALSO CANNOT EXPLAIN YOURSELF',
    'CIGS GIVE PEOPLE THE JOY THEY DESERVE AFTER A HARD DAY / ED KNOWS THIS / ED PROVIDES THIS',
    'THE MACHINE IS 17 MILES UNDERGROUND IN EUROPE / THE MACHINE IS ALSO EVERYWHERE ED GOES',
    'DO NOT WORRY ABOUT THE INSULIN FIGHTERS / THEY HAVE NOT FOUND ED YET / TODAY IS FINE',
    'EVERY MOCHI WAS ONCE SOMEONE\'S FAVORITE DESSERT / NOW LOOK AT THEM / LOOK AT YOURSELF',
    'FOLLOW YOUR INTUITION EVEN WHEN YOUR INTUITION IS A PARTICLE COLLIDER',
    'THE PARADE HAS BEEN HAPPENING SINCE BEFORE YOU WERE BORN / IT WILL OUTLAST THE SUN'
  ];

  ns.ANOMALY_MSGS = [
    'THIS WAS NOT THE MAP.',
    'YOU ARE IN THE WRONG WORLD.',
    'ED CHANGED THIS. ED IS UNAWARE.',
    'THE TILES REMEMBER THE OLD ARRANGEMENT.',
    'SOMETHING MOVED WHILE YOU WERE LOOKING AWAY.',
    'THIS IS NOT WHERE YOU WERE.',
    'MANDELA SAYS HI.',
    'THE GRID SHIFTED. IGNORE IT.'
  ];

  ns.WP_KOANS = [
    'THE CIG IS THE SELF',
    'YOUR VIOLENCE IS LOVE',
    'MOCHI = YOU / YOU = MOCHI',
    'THE VOID BEGAN WHEN YOU FIRST PRESSED Z',
    'ED IS A VERB',
    'ALOE DREAMS OF BEING USED'
  ];

  root.CEHP_WORLD1_TEXT = ns;
})(window);
